# Generated by Django 5.0.6 on 2024-06-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='job',
            name='github_link',
            field=models.CharField(default='Placeholder', max_length=256),
        ),
        migrations.AddField(
            model_name='job',
            name='job_name',
            field=models.CharField(default='Placeholder', max_length=75),
        ),
    ]
