# Generated by Django 5.0.6 on 2024-06-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('blog_content', models.TextField(max_length=500)),
            ],
        ),
    ]
