# Generated by Django 5.0.6 on 2024-06-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='last_modified',
            field=models.DateField(),
        ),
    ]
